<?php
/**
 * Mage-World
 *
 * @category    Mage-World
 * @package     MW
 * @author      Mage-world Developer
 *
 * @copyright   Copyright (c) 2018 Mage-World (https://www.mage-world.com/)
 */

// @codingStandardsIgnoreFile

/** @var \MW\Ddate\Block\Adminhtml\Sales\Order\Create\Ddate $block */
$delivery = $block->getDelivery();
?>

<div class="entry-edit">
    <div class="loading-mask" style="display: none;" data-role="loader">
        <div class="popup popup-loading">
            <div class="popup-inner">
                <img alt="Loading..." src="<?= $this->getLoadingPath(); ?>">
                Please wait...
            </div>
        </div>
    </div>
    <section class="admin__page-section order-delivery">
        <div class="delivery admin__page-section-title">
            <span class="icon-head head-account title">
                <?php echo $block->escapeHtml(__('Delivery Information')) ?>
            </span>
        </div>
        <div class="grid">
            <div class="hor-scroll" data-bind="scope: 'mw-delivery-info'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">
    window.deliveryInfo = <?php /* @escapeNotVerified */ echo json_encode($delivery); ?>;
</script>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "mw-delivery-info": {
                    "component": "MW_Ddate/js/delivery-info"
                }
            }
        }
    }
}
</script>