<?php
/**
 * Mage-World
 *
 * @category    Mage-World
 * @package     MW
 * @author      Mage-world Developer
 *
 * @copyright   Copyright (c) 2018 Mage-World (https://www.mage-world.com/)
 */

// @codingStandardsIgnoreFile

/** @var \MW\Ddate\Block\Adminhtml\Sales\Order\View\Tab\Information $block */
$delivery = $block->getDelivery();
?>

<div class="entry-edit">
    <div class="loading-mask" style="display: none;" data-role="loader">
        <div class="popup popup-loading">
            <div class="popup-inner">
                <img alt="Loading..." src="<?= $this->getLoadingPath(); ?>">
                Please wait...
            </div>
        </div>
    </div>
    <section class="admin__page-section order-delivery">
        <div class="delivery admin__page-section-title">
            <span class="icon-head head-account title">
                <?php echo $block->escapeHtml(__('Delivery Information')) ?>
            </span>
        </div>
        <div class="grid">
            <div class="hor-scroll">
                <div id="delivery_date_form">
                    <ul>
                        <li class="delivery">
                            <div class="delivery_time_date">
                                <label for="mw_delivery_date"><?php echo $block->escapeHtml(__('Date to delivery')) ?></label>
                                <p class="datetime-delivery">
                                    <input readonly="readonly" id="mw_delivery_date" class="admin__control-text"
                                           type="text" size="17" name="delivery-date"/>
                                </p>
                            </div>
                            <div class="delivery_time_date select-time">
                                <label for="mw_delivery_time"><?php echo $block->escapeHtml(__('Time to delivery')) ?></label>
                                <p class="datetime-delivery">
                                    <select class="select admin__control-select" id="mw_delivery_time" name="delivery_time" style="width: 200px">
                                    </select>
                                </p>
                            </div>
                        </li>
<!--                        <li class="mw_sercurity-box">-->
<!--                            <div class="input-box">-->
<!--                                <label for="security_code">--><?php //echo $block->escapeHtml(__('Security access code (Buildings/gated communities)')) ?><!--</label>-->
<!--                                <p class="security-code-delivery">-->
<!--                                    <input id="security_code" class="osc-additional-data input-text"-->
<!--                                           type="text" size="25" name="security_code" required/>-->
<!--                                </p>-->
<!--                            </div>-->
<!--                        </li>-->
                        <?php if ($delivery['config']['isEnableComment']) : ?>
                        <li class="mw_comment">
                            <div class="input-box">
                                <label for="security_code"><?php echo $block->escapeHtml(__('Delivery Comment')) ?></label>
                                <p class="comment-delivery">
                                    <textarea rows="5" id="mw_delivery_comment" class="input-text admin__control-text" type="text" name="mw_delivery_comment"></textarea>
                                </p>
                            </div>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">
    window.deliveryInfo = <?php /* @escapeNotVerified */ echo json_encode($delivery); ?>;

    require([
        'jquery',
        'MW_Ddate/js/api'
    ], function ($, Api) {
        function disableDate (date) {
            var day = date.getDate();
            var month = date.getMonth() + 1;
            var year = date.getFullYear();
            var currentDateText = year+"-"+("0" + (month)).slice(-2)+"-"+("0" + (day)).slice(-2);

            var isDeliveryOnSat = window.deliveryInfo.config.deliverSaturdays;
            var isDeliveryOnSun = window.deliveryInfo.config.deliverSundays;
            var weekday = date.getDay();
            if((isDeliveryOnSat == '0' && weekday == 6) || (isDeliveryOnSun == '0' && weekday == 0)){
                return [false];
            }

            var disableDate = window.deliveryInfo.config.disableDate;
            if (disableDate) {
                var disableDateArray = disableDate.split(';');
                // Now check if the current date is in disabled dates array.

                if ($.inArray(currentDateText, disableDateArray) != -1 ) {
                    return [false];
                } else {
                    return [true];
                }
            } else {
                return [true];
            }
        }

        function initDatetimePicker (){
            var currentDate = new Date();
            var year = currentDate.getFullYear();
            var month = currentDate.getMonth();
            var day = currentDate.getDate();

            var limitWeeks = window.deliveryInfo.config.limitWeeks;
            currentDate.setDate(day + limitWeeks*7);
            var maxDate = currentDate;
            var self = this;
            $("#mw_delivery_date").calendar({
                showsTime: false,
                controlType: 'select',
                timeFormat: 'HH:mm TT',
                dateFormat: 'yyyy-MM-dd',
                showTime: false,
                minDate: new Date(year, month, day, '00', '00', '00', '00'),
                maxDate: new Date(maxDate.getFullYear(), maxDate.getMonth(), maxDate.getDate(), '00', '00', '00', '00'),
                beforeShowDay: disableDate,
                onSelect: function (dateText, evt) {
                    if(evt){
                        var param = {
                            ddate: evt.currentYear+"-"+("0" + (evt.currentMonth+1)).slice(-2)+"-"+("0" + (evt.currentDay)).slice(-2)
                        };
                        var url = window.deliveryInfo.loadTimeUrl;
                        Api.post(url, param, function (res) {
                            var res = JSON.parse(res);
                            $('#mw_delivery_time').html('');
                            $.each(res, function (i, item) {
                                $('#mw_delivery_time').append($('<option>', {
                                    value: item.value,
                                    text : item.label
                                }));
                            });
                        });
                    }
                }
            });
        }
        $(document).ready(function () {
            initDatetimePicker();
        });
    });
</script>