<?php $ddate = $block->getDdate(); ?>
<?php if ($ddate): ?>
<div class="block block-order-delivery-view">
    <div class="block-title">
        <strong><?php echo $block->escapeHtml(__('Delivery Date Information')); ?></strong>
    </div>
    <div class="block-content">
        <img class="unavailableimg" src="<?php echo $block->escapeHtml($block->getViewFileUrl('MW_Ddate::images/ddate_selected_date.png')); ?>">
        <strong><?php echo $block->escapeHtml(__('Delivery Date: ')); ?></strong> <span><?php echo $block->escapeHtml($ddate->getDdate()); ?></span><br>
        <img class="unavailableimg" src="<?php echo $block->escapeHtml($block->getViewFileUrl('MW_Ddate::images/ddate_selected_time.png')); ?>">
        <strong><?php echo $block->escapeHtml(__('Delivery Time: ')); ?></strong><span><?php echo $block->escapeHtml($ddate->getDtimetext()); ?></span>
    </div>
</div>
<?php endif; ?>